### ISSUE TITLE
Semi-Stuck in walls after jumping

### ISSUE THREAD

**Issue by TheDiemer** [sjwalter2/komae1#2]
If you double-jump while facing away from the wall, but right next to it, and then turn to face the wall you get stuck.

@sjwalter2 and I theorized that the collision boxes for the sprites (jumping vs falling) is enough for it not to think it was colliding but enough for it to get stuck when you turn into the box.

**Comment by sjwalter2** [comment]
fixed. there were an embarrassing number of causes for this... my collision code was a mess. https://github.com/sjwalter2/komae1/commit/8670b33028d8264ada5031210f8cefc936d25912
